# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='zip',
            new_name='codezip',
        ),
    ]
